flow-php/etl-transformer

README.md
composer.lock
src/Flow/ETL/Transformer/Filter/Filter/EntryEqualsTo.php
tests/Flow/ETL/Transformer/Filter/Tests/Unit/Filter/EntryEqualsToTest.php
tests/Flow/ETL/Transformer/Filter/Tests/Unit/FilterRowsTest.php

<h4>Added</h4>
</ul> 
</ul>
<li>Make StringEntryEqualsTo more generic EntryEqualsTo</li>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Replace StringEntryEqualsTo with EntryEqualsTo

---

README.md
src/Flow/ETL/Transformer/Filter/FilterRows.php

<h4>Added</h4>
</ul> 
<li>Add missing implement statement</li>
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Implement Transformer interface

---

README.md
composer.json
composer.lock
infection.json
src/Flow/ETL/Transformer/ArrayUnpackTransformer.php
tests/Flow/ETL/Transformer/Tests/Unit/ArrayUnpackTransformerTest.php

<h4>Added</h4>
<li>ArrayUnpackTransformer</li>
</ul> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Added ArrayUnpackTransformer

---

README.md
src/Flow/ETL/Transformer/KeepEntriesTransformer.php
tests/Flow/ETL/Transformer/Tests/Unit/KeepEntriesTransformerTest.php

<h4>Added</h4>
<li>KeepEntriesTransformer</li>
</ul> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

KeepEntriesTransformer

---

src/Flow/ETL/Transformer/ChainTransformer.php
tests/Flow/ETL/Transformer/Tests/Unit/ChainTransformerTest.php

<h4>Added</h4>
<li>TransformerChain</li>
</ul> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Added transformer chain

---

README.md
infection.json
src/Flow/ETL/Transformer/Cast/CastEntry.php
src/Flow/ETL/Transformer/Cast/CastJsonToArray.php
src/Flow/ETL/Transformer/Cast/CastToArray.php
src/Flow/ETL/Transformer/Cast/CastToDate.php
src/Flow/ETL/Transformer/Cast/CastToDateTime.php
src/Flow/ETL/Transformer/Cast/CastToInteger.php
src/Flow/ETL/Transformer/Cast/CastToJson.php
src/Flow/ETL/Transformer/Cast/CastToString.php
src/Flow/ETL/Transformer/CastTransformer.php
tests/Flow/ETL/Transformer/Tests/Unit/CastTransformerTest.php

<h4>Added</h4>
<li>CastTransformer - cast entries of one types into another</li>
</ul> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Added CastTransformer

---

composer.lock
src/Flow/ETL/Transformer/ArrayUnpackTransformer.php
tests/Flow/ETL/Transformer/Tests/Unit/ArrayUnpackTransformerTest.php

<h4>Added</h4>
</ul> 
</ul>
<li>ArrayUnpackTransformer transforms floats into FloatEntry, not strings</li>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Added support for FloatEntry to ArrayUnpackTransformer

---

README.md
src/Flow/ETL/Transformer/StringFormatTransformer.php
tests/Flow/ETL/Transformer/Tests/Unit/StringFormatTransformerTest.php

<h4>Added</h4>
<li>StringFormatTransformer</li>
</ul> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Added StringFormatTransformer

---

README.md
infection.json
src/Flow/ETL/Transformer/Filter/Filter/All.php
src/Flow/ETL/Transformer/Filter/Filter/Any.php
src/Flow/ETL/Transformer/Filter/Filter/EntryNotEqualsTo.php
src/Flow/ETL/Transformer/Filter/Filter/EntryNotNumber.php
src/Flow/ETL/Transformer/Filter/Filter/EntryNumber.php
src/Flow/ETL/Transformer/Filter/Filter/Opposite.php
tests/Flow/ETL/Transformer/Tests/Unit/Filter/AllTest.php
tests/Flow/ETL/Transformer/Tests/Unit/Filter/AnyTest.php
tests/Flow/ETL/Transformer/Tests/Unit/Filter/EntryEqualsToTest.php
tests/Flow/ETL/Transformer/Tests/Unit/Filter/EntryNotEqualsToTest.php
tests/Flow/ETL/Transformer/Tests/Unit/Filter/EntryNotNumberTest.php
tests/Flow/ETL/Transformer/Tests/Unit/Filter/EntryNumberTest.php
tests/Flow/ETL/Transformer/Tests/Unit/Filter/OppositeTest.php

<h4>Added</h4>
<li>All - Filter for FilterTransformer</li>
<li>Any - Filter for FilterTransformer</li>
<li>Opposite - Filter for FilterTransformer</li>
<li>All - Filter for FilterTransformer</li>
<li>EntryNumber - Filter for FilterTransformer</li>
<li>EntryNotNumber - Filter for FilterTransformer</li>
<li>EntryNotEquals - Filter for FilterTransformer</li>
</ul> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Added new filters to FilterTransformer

---

src/Flow/ETL/Transformer/Cast/CastToDateTime.php
tests/Flow/ETL/Transformer/Tests/Unit/CastTransformerTest.php

<h4>Added</h4>
<li>CastToDateTime - timezone in case it's just a string "2020-01-01 00:00:00"</li>
<li>CastToDateTime - to timezone in case string needs to be converted to different tz "2020-01-01 00:00:00+00:00"</li>
</ul> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Added possibility to set datetime tz and convert to different tz

---

src/Flow/ETL/Transformer/Cast/CastEntry.php
src/Flow/ETL/Transformer/Cast/CastJsonToArray.php
src/Flow/ETL/Transformer/Cast/CastToArray.php
src/Flow/ETL/Transformer/Cast/CastToDate.php
src/Flow/ETL/Transformer/Cast/CastToDateTime.php
src/Flow/ETL/Transformer/Cast/CastToInteger.php
src/Flow/ETL/Transformer/Cast/CastToJson.php
src/Flow/ETL/Transformer/Cast/CastToString.php
src/Flow/ETL/Transformer/CastTransformer.php
tests/Flow/ETL/Transformer/Tests/Unit/CastTransformerTest.php

<h4>Added</h4>
</ul> 
</ul>
<li>mproved casting entries by allowing to cast more than one entry with single cast</li>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Improved casting entries by allowing to cast more than one entry with single cast

---

infection.json
src/Flow/ETL/Transformer/Cast/CastEntry.php
src/Flow/ETL/Transformer/Cast/CastJsonToArray.php
src/Flow/ETL/Transformer/Cast/CastToArray.php
src/Flow/ETL/Transformer/Cast/CastToDate.php
src/Flow/ETL/Transformer/Cast/CastToDateTime.php
src/Flow/ETL/Transformer/Cast/CastToInteger.php
src/Flow/ETL/Transformer/Cast/CastToJson.php
src/Flow/ETL/Transformer/Cast/CastToString.php
src/Flow/ETL/Transformer/CastTransformer.php
tests/Flow/ETL/Transformer/Tests/Unit/CastTransformerTest.php

<h4>Added</h4>
<li>Added possibility to handle nullable values in cast transformer</li>
</ul> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Added possibility to handle nullable values in cast transformer

---

src/Flow/ETL/Transformer/ArrayExpandTransformer.php
src/Flow/ETL/Transformer/ArrayUnpackTransformer.php
src/Flow/ETL/Transformer/DynamicEntryTransformer.php
src/Flow/ETL/Transformer/Factory/ArrayRowsFactory.php
src/Flow/ETL/Transformer/Factory/CastedRowsFactory.php
src/Flow/ETL/Transformer/Factory/NativeEntryFactory.php
src/Flow/ETL/Transformer/RowsFactory.php
tests/Flow/ETL/Transformer/Tests/Unit/DynamicEntryTransformerTest.php
tests/Flow/ETL/Transformer/Tests/Unit/Factory/ArrayRowsFactoryTest.php
tests/Flow/ETL/Transformer/Tests/Unit/Factory/CasedRowsFactoryTest.php

<h4>Added</h4>
<li>DynamicEntryTransformer</li>
</ul> 
</ul>
<li>RowsFactory create method now expects data</li>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Added dynamic entry transformer

---

README.md
src/Flow/ETL/Transformer/ArrayExpandTransformer.php
src/Flow/ETL/Transformer/CallbackRowTransformer.php
src/Flow/ETL/Transformer/CloneEntryTransformer.php
tests/Flow/ETL/Transformer/Tests/Unit/CallbackRowTransformerTest.php
tests/Flow/ETL/Transformer/Tests/Unit/CloneEntryTransformerTest.php

<h4>Added</h4>
<li>CloneEntryTransformer</li>
<li>CallbackRowTransformer</li>
</ul> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Added clone entry transformer

---

README.md
src/Flow/ETL/Transformer/Filter/Filter/EntryExists.php
tests/Flow/ETL/Transformer/Tests/Unit/Filter/EntryExistsTest.php
tests/Flow/ETL/Transformer/Tests/Unit/FilterRowsTransformerTest.php

<h4>Added</h4>
<li>EntryExists filter for FilterRowsTransformer</li>
</ul> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Added EntryExists filter

---

README.md
src/Flow/ETL/Transformer/ObjectMethodTransformer.php
tests/Flow/ETL/Transformer/Tests/Unit/ObjectMethodTransformerTest.php

<h4>Added</h4>
<li>ObjectMethodTransformer</li>
</ul> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Added ObjectMethodTransformer

---

README.md
src/Flow/ETL/Transformer/Accessor/ArrayAccessor.php
src/Flow/ETL/Transformer/ArrayAccessorTransformer.php
tests/Flow/ETL/Transformer/Tests/Unit/Accessor/ArrayAccessorTest.php
tests/Flow/ETL/Transformer/Tests/Unit/ArrayAccessorTransformerTest.php

<h4>Added</h4>
<li>ArrayAccessorTransformer</li>
</ul> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Added ArrayAccessorTransformer

---

README.md
src/Flow/ETL/Transformer/StringContactTransformer.php
tests/Flow/ETL/Transformer/Tests/Unit/StringContactTransformerTest.php

<h4>Added</h4>
<li>StringContactTransformer</li>
</ul> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Added StringContact transformer

---

README.md
src/Flow/ETL/Transformer/Accessor/ArrayAccessor.php
tests/Flow/ETL/Transformer/Tests/Unit/Accessor/ArrayAccessorTest.php

<h4>Added</h4>
<li>nullsafe operator to ArrayAccessor path</li>
</ul> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Added nullsafe operator to ArrayAccessor path

---

README.md
src/Flow/ETL/Transformer/Condition/All.php
src/Flow/ETL/Transformer/Condition/Any.php
src/Flow/ETL/Transformer/Condition/ArrayDotExists.php
src/Flow/ETL/Transformer/Condition/EntryExists.php
src/Flow/ETL/Transformer/Condition/EntryInstanceOf.php
src/Flow/ETL/Transformer/Condition/EntryNotNull.php
src/Flow/ETL/Transformer/Condition/EntryValueEqualsTo.php
src/Flow/ETL/Transformer/Condition/EntryValueGreaterOrEqualThan.php
src/Flow/ETL/Transformer/Condition/EntryValueGreaterThan.php
src/Flow/ETL/Transformer/Condition/EntryValueLessOrEqualThan.php
src/Flow/ETL/Transformer/Condition/EntryValueLessThan.php
src/Flow/ETL/Transformer/Condition/None.php
src/Flow/ETL/Transformer/Condition/Opposite.php
src/Flow/ETL/Transformer/Condition/RowCondition.php
src/Flow/ETL/Transformer/ConditionalTransformer.php
src/Flow/ETL/Transformer/StaticEntryTransformer.php
tests/Flow/ETL/Transformer/Tests/Unit/ConditionalTransformerTest.php

<h4>Added</h4>
<li>ConditionalTransformer</li>
<li>StaticEntryTransformer</li>
</ul> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>
The conditional transformer is a powerful and very flexible way to transform selected Rows in a specific way leaving other rows untouched.

Added Conditional and StaticEntry Transformers

---

README.md
src/Flow/ETL/Transformer/ArraySortTransformer.php
tests/Flow/ETL/Transformer/Tests/Unit/ArraySortTransformerTest.php

<h4>Added</h4>
<li>ArraySortTransformer</li>
</ul> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Added ArraySortTransformer

---

README.md
src/Flow/ETL/Transformer/ArrayMergeTransformer.php
tests/Flow/ETL/Transformer/Tests/Unit/ArrayMergeTransformerTest.php

<h4>Added</h4>
<li>ArrayMergeTransformer</li>
</ul> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Added ArrayMerge transformer

---

README.md
src/Flow/ETL/Transformer/ArrayReverseTransformer.php
tests/Flow/ETL/Transformer/Tests/Unit/ArrayReverseTransformerTest.php

<h4>Added</h4>
<li>ArrayReverseTransformer</li>
</ul> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Added array reverse transformer

---

README.md
src/Flow/ETL/Transformer/MathOperationTransformer.php
tests/Flow/ETL/Transformer/Tests/Unit/MathOperationTransformerTest.php

<h4>Added</h4>
<li>MathOperationTransformer</li>
</ul> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Added MathOperationTransformer

---

README.md
src/Flow/ETL/Transformer/ArrayDotRenameTransformer.php
src/Flow/ETL/Transformer/Rename/ArrayKeyRename.php
src/Flow/ETL/Transformer/Rename/EntryRename.php
src/Flow/ETL/Transformer/RenameEntriesTransformer.php
tests/Flow/ETL/Transformer/Tests/Unit/ArrayDotRenameTransformerTest.php
tests/Flow/ETL/Transformer/Tests/Unit/RenameEntriesTransformerTest.php

<h4>Added</h4>
<li>ArrayDotRename transformer</li>
</ul> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Add ArrayDotRename transformer

---

README.md
src/Flow/ETL/Transformer/GroupToArrayTransformer.php
tests/Flow/ETL/Transformer/Tests/Unit/GroupToArrayTransformerTest.php

<h4>Added</h4>
<li>GroupToArrayTransformer</li>
</ul> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Added GroupToArrayTransformer

---

README.md
src/Flow/ETL/Transformer/StringEntryValueCaseConverterTransformer.php
tests/Flow/ETL/Transformer/Tests/Unit/StringEntryValueCaseConverterTransformerTest.php

<h4>Added</h4>
<li>Added StringEntryValueCaseConverterTransformer</li> 
</ul> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Added StringEntryValueCaseConverterTransformer

---

README.md
src/Flow/ETL/Transformer/ArrayKeysStyleConverterTransformer.php
src/Flow/ETL/Transformer/EntryNameStyleConverterTransformer.php
src/Flow/ETL/Transformer/StyleConverter/ArrayKeyConverter.php
src/Flow/ETL/Transformer/StyleConverter/StringStyles.php
tests/Flow/ETL/Transformer/Tests/Unit/ArrayKeysStyleTransformerTest.php
tests/Flow/ETL/Transformer/Tests/Unit/CaseConverter/ArrayKeyConverterTest.php
tests/Flow/ETL/Transformer/Tests/Unit/EntryNameStyleConverterTransformerTest.php

<h4>Added</h4>
</ul> 
</ul>
<li>Renamed transformers</li> 
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Renamed transformers

---

src/Flow/ETL/Transformer/ConditionalTransformer.php
tests/Flow/ETL/Transformer/Tests/Integration/ConditionalTransformerTest.php

<h4>Added</h4>
</ul> 
</ul>
<li>ConditionalTransformer returns Rows' flatMap now</li>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

ConditionalTransformer returns all transformed rows

---

.github/dependabot.yml

<h4>Added</h4>
</ul> 
<li>Added dependabot for tool</li>
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Add dependabot for tools

---

composer.json
composer.lock
src/Flow/ETL/Transformer/ArrayMergeTransformer.php
src/Flow/ETL/Transformer/ArrayReverseTransformer.php
src/Flow/ETL/Transformer/Cast/EntryCaster/AnyToArrayEntryCaster.php
src/Flow/ETL/Transformer/Cast/EntryCaster/AnyToFloatEntryCaster.php
src/Flow/ETL/Transformer/Cast/EntryCaster/AnyToIntegerEntryCaster.php
src/Flow/ETL/Transformer/Cast/EntryCaster/AnyToJsonEntryCaster.php
src/Flow/ETL/Transformer/Cast/EntryCaster/AnyToStringEntryCaster.php
src/Flow/ETL/Transformer/Cast/EntryCaster/DateTimeToStringEntryCaster.php
src/Flow/ETL/Transformer/Cast/EntryCaster/JsonToArrayEntryCaster.php
src/Flow/ETL/Transformer/Cast/EntryCaster/StringToDateTimeEntryCaster.php
src/Flow/ETL/Transformer/Cast/ValueCaster/AnyToFloatCaster.php
src/Flow/ETL/Transformer/Cast/ValueCaster/AnyToIntegerCaster.php
src/Flow/ETL/Transformer/Cast/ValueCaster/AnyToStringCaster.php
src/Flow/ETL/Transformer/Condition/ArrayDotValueGreaterOrEqualThan.php
src/Flow/ETL/Transformer/Condition/ArrayDotValueGreaterThan.php
src/Flow/ETL/Transformer/Condition/ArrayDotValueLessOrEqualThan.php
src/Flow/ETL/Transformer/Condition/ArrayDotValueLessThan.php
src/Flow/ETL/Transformer/Factory/ArrayRowsFactory.php
src/Flow/ETL/Transformer/Factory/CastedRowsFactory.php
src/Flow/ETL/Transformer/Factory/NativeEntryFactory.php
src/Flow/ETL/Transformer/RowsFactory.php
src/Flow/ETL/Transformer/StringConcatTransformer.php
src/Flow/ETL/Transformer/StringFormatTransformer.php
tools/composer.lock

<h4>Added</h4>
</ul> 
<li>PHP errors</li> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Fix PHPStan errors

---

src/Flow/ETL/Transformer/ArrayKeysStyleConverterTransformer.php
src/Flow/ETL/Transformer/Filter/Filter/Callback.php
src/Flow/ETL/Transformer/StyleConverter/ArrayKeyConverter.php

<h4>Added</h4>
</ul> 
<li>Psalm errors</li> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Fix Psalm errors

---

composer.lock
src/Flow/ETL/Transformer/ArrayExpandTransformer.php
src/Flow/ETL/Transformer/ArrayReverseTransformer.php
src/Flow/ETL/Transformer/ArraySortTransformer.php
src/Flow/ETL/Transformer/ArrayUnpackTransformer.php
src/Flow/ETL/Transformer/Cast/CastEntries.php
src/Flow/ETL/Transformer/DynamicEntryTransformer.php
src/Flow/ETL/Transformer/KeepEntriesTransformer.php
src/Flow/ETL/Transformer/NullStringIntoNullEntryTransformer.php
src/Flow/ETL/Transformer/RemoveEntriesTransformer.php
src/Flow/ETL/Transformer/RenameEntriesTransformer.php
src/Flow/ETL/Transformer/StringEntryValueCaseConverterTransformer.php
src/Flow/ETL/Transformer/StringFormatTransformer.php

<h4>Added</h4>
</ul> 
</ul>
<li>Reduce recreating from scratch entries in transformers</li>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Reduce recreating from scratch entries in transformers

---

README.md
composer.lock
src/Flow/ETL/Transformer/ArrayCollectionGetTransformer.php
tests/Flow/ETL/Transformer/Tests/Unit/ArrayCollectionGetTransformerTest.php
tests/Flow/ETL/Transformer/Tests/Unit/ArrayKeysStyleConverterTransformerTest.php
tests/Flow/ETL/Transformer/Tests/Unit/StaticEntryTransformerTest.php

<h4>Added</h4>
<li>ArrayCollectionGetTransformer</li>
</ul> 
</ul>
<li>README now points to tests as the most up to date usage examples of each  transformer</li>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Array collection get transformer

---

README.md
src/Flow/ETL/Transformer/ArrayCollectionMergeTransformer.php
tests/Flow/ETL/Transformer/Tests/Unit/ArrayCollectionMergeTransformerTest.php

<h4>Added</h4>
<li>ArrayCollectionMergeTransformer</li>
</ul> 
</ul>
</ul>  
</ul>
</ul>  
</ul>     
</div>
<hr/>

Array collection merge transformer
